services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: python -Xfrozen_modules=off -m fastapi dev --host 0.0.0.0 src/uv_docker_example
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: uv.lock

  debug:
    build: .
    ports:
      - "8000:8000"
      - "5678:5678"
    command: python -Xfrozen_modules=off -m debugpy --listen 0.0.0.0:5678 --wait-for-client -m fastapi dev --host 0.0.0.0 src/uv_docker_example
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: uv.lock
